(()=>{"use strict";const f=document.querySelector("#funnel"),steps=[...document.querySelectorAll(".step")],prog=[...document.querySelectorAll("#progress li")],tables=f.tables,chairs=f.chairs,subtotal=document.querySelector("#subtotal"),rental=document.querySelector("#rentalEstimate"),total=document.querySelector("#totalEstimate"),review=document.querySelector("#review"),confirm=document.querySelector("#confirm"),msg=document.querySelector("#submitMsg"),success=document.querySelector("#success"),leadRef=document.querySelector("#leadRef");const STORE="bwrFunnelV2",SUB="bwrSubmissionId";let step=0,pkg=false,busy=false;const attribution=getAttribution();restore();price();show(step);
document.querySelectorAll("[data-next]").forEach(b=>b.onclick=()=>{if(valid(step)){save();show(Math.min(5,step+1))}});
document.querySelectorAll("[data-back]").forEach(b=>b.onclick=()=>{save();show(Math.max(0,step-1))});
document.querySelectorAll("[data-for]").forEach(b=>b.onclick=()=>{const i=document.getElementById(b.dataset.for);i.value=Math.max(0,Math.floor(+i.value+(+b.dataset.delta)));pkg=false;price();save()});
[tables,chairs].forEach(i=>i.oninput=()=>{i.value=Math.max(0,Math.floor(+i.value||0));pkg=false;price();save()});
document.querySelector("#package").onclick=()=>{tables.value=3;chairs.value=20;pkg=true;price();save()};
f.oninput=save;f.onchange=save;f.onsubmit=submit;document.querySelector("#newRequest").onclick=reset;
function calc(){const t=+tables.value||0,c=+chairs.value||0;if(pkg&&t===3&&c===20)return{t,c,s:50,mode:"3 Tables + 20 Chairs package"};const bulk=t>=3&&c>=20;return{t,c,s:t*(bulk?6:8)+c*(bulk?1.5:2),mode:bulk?"Bulk pricing":"Standard pricing"}}
function price(){const x=calc();subtotal.textContent=money(x.s);rental.textContent=money(x.s)}
function show(n){step=n;steps.forEach((s,i)=>{s.hidden=i!==n;s.classList.toggle("active",i===n)});prog.forEach((p,i)=>{p.classList.toggle("active",i===n);p.classList.toggle("done",i<n)});if(n===3){const x=calc();rental.textContent=money(x.s);total.textContent=money(x.s)+" + delivery"}if(n===5)render();scrollTo({top:0,behavior:"smooth"})}
function valid(n){clearErrors();if(n===0){const x=calc();if(!x.t&&!x.c)return err("itemsErr","Select at least one table or chair.")}if(n===1){const a=f.startDate.value,b=f.startTime.value,c=f.endDate.value,d=f.endTime.value;if(!a||!b||!c||!d)return err("periodErr","Enter the complete rental start and end date/time.");if(!(new Date(c+"T"+d)>new Date(a+"T"+b)))return err("periodErr","The rental end must be after the rental start.")}if(n===2){if(!f.address1.value.trim()||!f.city.value.trim()||!f.state.value.trim()||!/^[0-9]{5}(-[0-9]{4})?$/.test(f.zipCode.value.trim()))return err("locationErr","Enter the complete delivery address, including a valid ZIP Code.")}if(n===4){if(!f.name.value.trim())return err("contactErr","Enter your name.");if(!f.mobile.value.trim())return err("contactErr","Enter the mobile number where Big W should text you.")}return true}
function payload(){const x=calc(),a={address1:f.address1.value.trim(),address2:f.address2.value.trim(),city:f.city.value.trim(),state:f.state.value.trim().toUpperCase(),zipCode:f.zipCode.value.trim()};a.full=[a.address1,a.address2,a.city+", "+a.state+" "+a.zipCode].filter(Boolean).join(", ");return{clientSubmissionId:getSub(),items:{tables:x.t,chairs:x.c,packageSelected:pkg,pricingMode:x.mode},rentalPeriod:{startDate:f.startDate.value,startTime:f.startTime.value,endDate:f.endDate.value,endTime:f.endTime.value},deliveryAddress:a,estimate:{rentalSubtotal:x.s,deliveryAmount:null,deliveryStatus:"PENDING_DISTANCE_CALCULATION",estimatedTotal:null,deliveryRatePerMile:1.5},name:f.name.value.trim(),mobile:f.mobile.value.trim(),notes:f.notes.value.trim(),attribution}}
function render(){const d=payload(),x=calc(),items=[x.t?x.t+" table"+(x.t===1?"":"s"):"",x.c?x.c+" chair"+(x.c===1?"":"s"):""].filter(Boolean).join(" + ");review.innerHTML=`<div><span><small>ITEMS</small>${esc(items)}</span><strong>${money(x.s)}</strong></div><div><span><small>RENTAL PERIOD</small>${esc(fmt(d.rentalPeriod.startDate,d.rentalPeriod.startTime))}<br>to ${esc(fmt(d.rentalPeriod.endDate,d.rentalPeriod.endTime))}</span><strong>${esc(x.mode)}</strong></div><div><span><small>DELIVERY</small>${esc(d.deliveryAddress.full)}</span><strong>Pending distance</strong></div><div><span><small>CONTACT</small>${esc(d.name)}<br>${esc(d.mobile)}</span><strong>Follow up by text</strong></div>`}
async function submit(e){e.preventDefault();if(busy||!valid(4))return;const url=window.BWR_CONFIG?.leadApiUrl||"";if(!/^https:\/\/script\.google\.com\/macros\/s\/.+\/exec$/.test(url))return submitErr("The lead notification service has not been configured yet.");setBusy(true);try{const r=await fetch(url,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(payload()),redirect:"follow"}),j=await r.json();if(!j.ok)throw Error(j.message||"Your request could not be sent.");sessionStorage.removeItem(STORE);sessionStorage.removeItem(SUB);f.hidden=true;document.querySelector(".progress").hidden=true;document.querySelector(".intro").hidden=true;leadRef.textContent=j.leadId||"Received";success.hidden=false;scrollTo({top:0,behavior:"smooth"})}catch(e){submitErr(e.message||"Your request could not be sent. Please try again.")}finally{setBusy(false)}}
function save(){const v={};new FormData(f).forEach((x,k)=>v[k]=x);sessionStorage.setItem(STORE,JSON.stringify({step,pkg,values:v,tables:+tables.value||0,chairs:+chairs.value||0}))}
function restore(){try{const s=JSON.parse(sessionStorage.getItem(STORE)||"null");if(!s)return;step=Math.max(0,Math.min(5,+s.step||0));pkg=!!s.pkg;Object.entries(s.values||{}).forEach(([k,v])=>{if(f.elements[k])f.elements[k].value=v});tables.value=s.tables||0;chairs.value=s.chairs||0}catch(_){}}
function reset(){f.reset();f.state.value="TX";tables.value=0;chairs.value=0;pkg=false;sessionStorage.removeItem(STORE);sessionStorage.removeItem(SUB);success.hidden=true;f.hidden=false;document.querySelector(".progress").hidden=false;document.querySelector(".intro").hidden=false;price();show(0)}
function getSub(){let id=sessionStorage.getItem(SUB);if(!id){id=crypto.randomUUID?crypto.randomUUID():Date.now()+"-"+Math.random();sessionStorage.setItem(SUB,id)}return id}
function getAttribution(){const q=new URLSearchParams(location.search),r=document.referrer||"";let s=q.get("utm_source")||"";if(!s)s=/google\./i.test(r)?"Google":/facebook\.|fb\./i.test(r)?"Facebook":r?"Referral":"Direct";return{leadSource:s,sourceDetail:q.get("source_detail")||"",landingPage:location.href,referrer:r,utmSource:q.get("utm_source")||"",utmMedium:q.get("utm_medium")||"",utmCampaign:q.get("utm_campaign")||"",utmContent:q.get("utm_content")||"",utmTerm:q.get("utm_term")||""}}
function fmt(d,t){return new Date(d+"T"+t+":00").toLocaleString([],{month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit"})}function money(x){return"$"+(+x).toFixed(2)}function esc(x){return String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}function clearErrors(){["itemsErr","periodErr","locationErr","contactErr"].forEach(i=>{const e=document.getElementById(i);e.hidden=true;e.textContent=""});msg.hidden=true}function err(i,t){const e=document.getElementById(i);e.textContent=t;e.hidden=false;e.scrollIntoView({behavior:"smooth",block:"center"});return false}function submitErr(t){msg.textContent=t;msg.hidden=false;msg.scrollIntoView({behavior:"smooth",block:"center"})}function setBusy(v){busy=v;confirm.disabled=v;confirm.querySelector(".ready").hidden=v;confirm.querySelector(".working").hidden=!v}
})();
